name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.5

      - name: Install Dependencies
        run: |
          go mod tidy
          git diff --exit-code -- go.mod go.sum

      - name: Run Tests
        run: go test ./... -v

      - name: Run Race Detector
        run: go test -race ./...

      - name: Run Vet
        run: go vet ./...
